### ISSUE TITLE
npm install meshblu-connector-ws2811 installs 0.1.0

### ISSUE THREAD

**Issue by shortbloke** [jamesbulpin/meshblu-connector-ws2811#2]
The latest version appears to be 0.2.2 which I can get if I download this via git. However the latest published version is still 0.1.0. 

I'm not sure what specifically needs to be done to update a npm package, but suspect you need to do it.

**Comment by jamesbulpin** [comment]
I'm not keeping npm up to date - the "official" way to get the connector is via the packaged Octoblu installer via app.octoblu.com
