### ISSUE TITLE
Clarify contents of meshblu.json

### ISSUE THREAD

**Issue by shortbloke** [jamesbulpin/meshblu-connector-ws2811#3]
Setting up this project I created a meshblu.json file containing:
```bash
{
  "uuid": "<MY UUID>",
  "token": "<MY TOKEN>",
  "protocol": "https",
  "hostname": "meshblu.octoblu.com",
  "port": 443
}
```
Upon starting node I'd see `meshblu-connector-runner` intermittently fail with a connection timeout. Changing the meshblu.json to:
```bash
{
  "uuid": "<MY UUID>",
  "token": "<MY TOKEN>",
  "resolveSrv": true
}
```
With this configuration `meshblu-connector-runner` appears to start up reliably. I'm guessing the difference is the protocol http/https/websockets. 

What is the correct/recommended contents for this json file.

**Comment by jamesbulpin** [comment]
Normally this is generated by the connector installer. In any case it's related to the core connector and not the WS2811 aspect.
